# site settings

title: Hyeontaek Lim
description: Jekyll theme for a beautiful online CV
taglong: I'm penetration tester at Codevector and I can test Web & App application.
tagshort: Jekyll theme
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/Captainjack-kor/Captainjack-kor.github.io

# author settings

author:
  name: Place Holder
  email: username@domain.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: username
  github: Captainjack-kor
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
