# site settings

title: 임현택
description: test
taglong: 현재 코드벡터에서 Web & App 모의 해킹 컨설턴트 업무를 하고 있는 임현택입니다. \n 오늘보다 내일 더 성장하는 삶을 목표로 하고 있습니다.
tagshort: Jekyll theme
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/Captainjack-kor/Captainjack-kor.github.io

# author settings

author:
  name: Place Holder
  email: username@domain.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: username
  github: username
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
