# site settings

title: 임현택
description: test2
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
url: https://github.com/Captainjack-kor
baseurl: ""
permalink: pretty
repo: https://github.com/Captainjack-kor

# author settings

author:
  name: Place Holder
  email: username@domain.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  #facebook: username
  github: Captainjack-kor
  #instagram: captainjackkr
  #linkedin: username
  #stackoverflow: 0000000/username
  terminal: \@iooi75

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
